services:
  postgres_payment_service:
    container_name: payment_service_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: payment_service_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5437:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  seq_payment_service:
    image: datalust/seq:latest
    container_name: payment_service_logging
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5343:5341
      - 8083:80

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  postgres-data:
  rabbitmq_data: