services:
  testservice.api:
    image: testservice.api
    build:
      context: .
      dockerfile: src/TestService.API/Dockerfile

  testsservice.api:
    image: testsservice.api
    build:
      context: .
      dockerfile: ./TestsService.API/Dockerfile

