services:
  postgres_tests_service:
    container_name: tests_service_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tests_service_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  seq_tests_service:
    image: datalust/seq:latest
    container_name: tests_service_logging
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5341
      - 8082:80

volumes:
  postgres-data:
  minio_data:  