services:
  postgres:
    container_name: tests_service_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tests_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
    
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5341
      - 8082:80

volumes:
  postgres-data:
  minio_data:  