name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: |
        dotnet restore ./TestsService/TestsService.sln
        dotnet restore ./UserService/UserService.sln
        dotnet restore ./PaymentService/PaymentService.sln

    - name: Build
      run: |
        dotnet build ./TestsService/TestsService.sln --configuration Release --no-restore
        dotnet build ./UserService/UserService.sln --configuration Release --no-restore
        dotnet build ./UserService/UserService.sln --configuration Release --no-restore