services:
  postgres_user_service:
    container_name: user_service_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: user_service_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  seq_user_service:
    image: datalust/seq:latest
    container_name: user_service_logging
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
volumes:
  postgres-data:
